<?php
namespace app\admin\controller;

class Index extends BaseController
{
    public $_table_title = '管理员';

    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

}
